### ISSUE TITLE
Unable to run shrinksam

### ISSUE THREAD

**Issue by Anto007** [bcthomas/shrinksam#1]
Hi,

I'm unable to run shrinksam as I keep getting this error:

antonycp@kw12957:~/tools/shrinksam-master$ ./shrinksam 
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

Any help here would be highly appreciated

**Comment by BBeamud** [comment]
Hello,
I get the same error that @Anto007. How did you solve it? 
Thank you.

**Comment by Anto007** [comment]
I just don't use this silly tool anymore. The latest available tools/versions of mapping tools such as Bowtie2 and BBmap provide options for not including non-mapped reads. On Bowtie2, just use the flag --no-unal during mapping and on BBmap, just use outm=Filename.sam during mapping.

**Comment by Anto007** [comment]
I just don't use this silly tool anymore. The latest available
tools/versions of mapping tools such as Bowtie2 and BBmap provide options
for not including non-mapped reads. On Bowtie2, just use the flag --no-unal
during mapping and on BBmap, just use outm=Filename.sam during mapping.
